import type { GuideArticle } from "@/lib/guides/types";

const verifiedAt = "September 20, 2026";

export const bestYtDlpGuiWindowsArticle: GuideArticle = {
  slug: "best-yt-dlp-gui-windows",
  faqs: [
    {
      question: "Is there an official yt-dlp GUI?",
      answer:
        "No. yt-dlp is a command-line project. The desktop apps compared here are independent frontends that use yt-dlp as an engine.",
    },
    {
      question: "Which yt-dlp GUI is best for Windows?",
      answer:
        "HalalDL is our Windows-first recommendation when you want local downloads, reusable presets, visible raw logs, and Full, Lite, or Portable packaging. Open Video Downloader and Parabolic are better starting points when cross-platform support matters more.",
    },
    {
      question: "Which tool is best for a large channel archive?",
      answer:
        "Tartube is the strongest fit in this list for long-running channel, playlist, and database workflows. It is more complex than a paste-and-download app, but that complexity serves archive management.",
    },
    {
      question: "Does the website send pasted media links to HalalDL?",
      answer:
        "The Open in HalalDL field validates the link in your browser and creates a local halaldl:// handoff. It does not put the media URL in a website route or analytics event.",
    },
  ],
  blocks: [
    {
      type: "callout",
      tone: "mint",
      title: "The short answer",
      body: "Choose HalalDL for a Windows-first local workflow with presets and visible logs. Choose Parabolic or Open Video Downloader for an easier cross-platform path. Choose Tartube for deep archive management. Choose yt-dlp itself when exact command-line control matters more than a GUI.",
    },
    {
      type: "paragraph",
      text: "There is no single best yt-dlp frontend for everybody. This comparison uses current official project pages and release records, names the tradeoffs, and avoids pretending that every capability is equivalent.",
    },
    {
      type: "callout",
      tone: "amber",
      title: "Responsible use",
      body: "Only download media you are allowed to access and save. Respect copyright, platform rules, and local law. Prefer an official project page or release over an anonymous download mirror.",
    },
    {
      type: "heading",
      level: 2,
      id: "comparison",
      text: "Compare the leading yt-dlp options",
    },
    {
      type: "comparison",
      title: "Best depends on the workflow",
      description:
        "HalalDL leads for Windows-first local control, but it is not the honest recommendation for every person. Filter the evidence, then use the official links to verify anything that matters to your setup.",
      verifiedAt,
      useCases: [
        {
          label: "Windows-first daily use",
          toolId: "halaldl",
          reason: "Full, Lite, and Portable choices, reusable presets, queues, and raw logs are designed around Windows 10/11.",
        },
        {
          label: "Cross-platform simplicity",
          toolId: "open-video-downloader",
          reason: "Windows, macOS, and Linux packages with playlists, cookies, presets, and automatic app/yt-dlp updates.",
        },
        {
          label: "Large archive management",
          toolId: "tartube",
          reason: "Its channel, playlist, folder, database, export, and backup model is intentionally deeper than a one-off downloader.",
        },
        {
          label: "Maximum exact control",
          toolId: "yt-dlp",
          reason: "The CLI exposes the engine directly, including archive files, cookies, output templates, and every supported option.",
        },
      ],
      tools: [
        {
          id: "halaldl",
          name: "HalalDL",
          shortName: "HalalDL",
          summary: "Windows-first, local-first GUI with clear build choices and visible troubleshooting output.",
          officialUrl: "https://github.com/Asdmir786/HalalDL",
          verifiedAt,
          filters: ["windows", "simple", "power", "archive", "open-source"],
          platforms: "Windows 10/11 x64.",
          installation: "Full or Lite EXE/MSI, Portable ZIP, and separate WinGet packages.",
          toolManagement: "Full and Portable manage yt-dlp, FFmpeg, aria2, and optional runtime support; Lite is bring-your-own.",
          playlists: "Preview supported playlists and select the entries to queue.",
          subtitles: "Subtitle and metadata choices are available through presets and download options.",
          cookies: "Supports cookie-assisted workflows for sources that require an authenticated browser session.",
          presets: "Reusable format, filename, folder, subtitle, and post-processing presets.",
          queues: "Explicit local queue with selection, retry, and raw progress.",
          rawLogs: "Full yt-dlp output remains visible, plus plain-language Download Doctor guidance.",
          archiveWorkflows: "Download archive, local Library folders, and source follows; lighter than Tartube's database model.",
          license: "MIT.",
          telemetryAndAccount: "No desktop telemetry and no account requirement. Website analytics is separate and privacy-limited when enabled.",
          releaseActivity: "v0.6.1 published September 20, 2026.",
          bestFor: "Windows users who want repeatable local workflows without hiding the underlying engine.",
          limitations: "No macOS or Linux build today; installers are not yet code-signed.",
          sources: [
            { label: "Project and feature documentation", url: "https://github.com/Asdmir786/HalalDL" },
            { label: "v0.6.1 release", url: "https://github.com/Asdmir786/HalalDL/releases/tag/v0.6.1" },
          ],
        },
        {
          id: "parabolic",
          name: "Parabolic",
          shortName: "Parabolic",
          summary: "Polished open-source frontend with native Windows and GNOME experiences.",
          officialUrl: "https://github.com/NickvisionApps/Parabolic",
          verifiedAt,
          filters: ["windows", "cross-platform", "simple", "power", "open-source"],
          platforms: "Windows, Linux, and macOS; separate WinUI and GNOME interfaces.",
          installation: "Platform releases, Flathub on Linux, and a Windows portable build.",
          toolManagement: "Current platform packages bundle or manage yt-dlp and supporting dependencies; package details vary by platform.",
          playlists: "Playlist discovery and per-item format/subtitle choices, with longer discovery on very large lists.",
          subtitles: "Subtitle search, selection, metadata, and embedding options are documented.",
          cookies: "Cookie file support; current Windows notes direct unsupported browser imports to manual text files.",
          presets: "Repeatable download preferences plus advanced discovery/download arguments.",
          queues: "Concurrent downloads and active-download views.",
          rawLogs: "Application logs and downloadable debugging information; less log-forward than HalalDL or the CLI.",
          archiveWorkflows: "History and exported M3U support, but not a Tartube-style channel database.",
          license: "MIT.",
          telemetryAndAccount: "No account requirement is documented for core use; the official README does not state a telemetry policy.",
          releaseActivity: "2026.5.0 published May 24, 2026.",
          bestFor: "People who want a modern, approachable GUI across Windows, Linux, and macOS.",
          limitations: "Platform interfaces differ, and very large playlist discovery can be slow when inspecting every item.",
          sources: [
            { label: "Project README", url: "https://github.com/NickvisionApps/Parabolic" },
            { label: "Release history", url: "https://github.com/NickvisionApps/Parabolic/releases" },
          ],
        },
        {
          id: "open-video-downloader",
          name: "Open Video Downloader",
          shortName: "OVD",
          summary: "Straightforward cross-platform GUI with broad packaging and automatic updates.",
          officialUrl: "https://github.com/jely2002/youtube-dl-gui",
          verifiedAt,
          filters: ["windows", "cross-platform", "simple", "open-source"],
          platforms: "Windows, macOS, and Linux, including x64 and Arm packages where listed.",
          installation: "GitHub installers/archives, WinGet, Homebrew, Microsoft Store, AppImage, DEB, and RPM paths.",
          toolManagement: "The app and yt-dlp update automatically in normal packages; Microsoft Store restrictions can affect yt-dlp updates.",
          playlists: "Entire playlists plus a configurable split threshold for large playlists.",
          subtitles: "Downloads subtitles and metadata, with format and quality controls.",
          cookies: "Cookie-file authentication is documented for private or rate-limited media.",
          presets: "Output locations, quality choices, filename presets, and custom templates.",
          queues: "Smart queueing balances multiple downloads.",
          rawLogs: "Progress and errors appear in the app; its public docs emphasize guided errors over a persistent raw-log workflow.",
          archiveWorkflows: "Playlist and queue support, not a long-running channel database.",
          license: "AGPL-3.0.",
          telemetryAndAccount: "No account requirement is documented for core use; the official README does not state a telemetry policy.",
          releaseActivity: "v3.2.1 published July 5, 2026; the 3.x line receives security fixes.",
          bestFor: "A broad cross-platform install path with common formats, cookies, playlists, and automatic updates.",
          limitations: "Less oriented toward archive databases or exposing every raw yt-dlp detail.",
          sources: [
            { label: "Project README", url: "https://github.com/jely2002/youtube-dl-gui" },
            { label: "v3 releases", url: "https://github.com/jely2002/youtube-dl-gui/releases" },
            { label: "Cookie tutorial", url: "https://github.com/jely2002/youtube-dl-gui/wiki/Tutorial%3A-Private-videos-%26-playlists" },
          ],
        },
        {
          id: "tartube",
          name: "Tartube",
          shortName: "Tartube",
          summary: "Database-driven manager for channels, playlists, libraries, and long-running archives.",
          officialUrl: "https://github.com/axcore/tartube",
          verifiedAt,
          filters: ["windows", "cross-platform", "power", "archive", "open-source"],
          platforms: "Windows, Linux, BSD, and macOS; Windows packages target 64-bit systems.",
          installation: "Windows installer/portable packages, Linux packages, PyPI, and source paths.",
          toolManagement: "Windows packages include core dependencies; yt-dlp and FFmpeg behavior is extensively configurable.",
          playlists: "Channels and playlists are first-class database objects with check/download operations.",
          subtitles: "Extensive downloader options expose yt-dlp subtitle and metadata workflows.",
          cookies: "Browser cookie import is documented; current Windows guidance notes browser-specific limits.",
          presets: "Deep global and per-media download option sets rather than a minimal preset picker.",
          queues: "Scheduled and batch operations for large collections.",
          rawLogs: "Power-user diagnostics and underlying downloader output are available.",
          archiveWorkflows: "Multiple databases, channel/playlist folders, imports/exports, backups, and repair tools.",
          license: "LGPL-2.1.",
          telemetryAndAccount: "No account requirement is documented for core use; the project README does not state a telemetry policy.",
          releaseActivity: "v2.5.231 published May 24, 2026; GitHub fixes can arrive more often than Windows installers.",
          bestFor: "People maintaining large collections, followed channels, or multiple archive databases.",
          limitations: "A heavier interface and setup model than paste-and-download GUIs; Windows package size is larger.",
          sources: [
            { label: "Project manual and README", url: "https://github.com/axcore/tartube" },
            { label: "Release history", url: "https://github.com/axcore/tartube/releases" },
          ],
        },
        {
          id: "stacher",
          name: "Stacher 7",
          shortName: "Stacher",
          summary: "Polished proprietary GUI with free core downloading and optional Premium library features.",
          officialUrl: "https://www.stacher.io/",
          verifiedAt,
          filters: ["windows", "cross-platform", "simple", "power", "archive"],
          platforms: "Windows, macOS, and Debian-based Linux.",
          installation: "Signed Windows setup, macOS DMGs, and Ubuntu/Debian package from the official site.",
          toolManagement: "Can install and keep yt-dlp updated and provides an automated FFmpeg installation path.",
          playlists: "Playlist downloads, table views, subscriptions, and multiple configurations.",
          subtitles: "yt-dlp configuration supports subtitle options; Premium Library adds subtitle indexing and search.",
          cookies: "Advanced yt-dlp configuration is available; usage gates apply to subscriptions and clipboard listening.",
          presets: "Multiple yt-dlp configurations, URL-pattern detection, and advanced custom arguments.",
          queues: "Download task manager, table/card views, and tray mini-window.",
          rawLogs: "Dedicated yt-dlp log viewer and manual execution terminal.",
          archiveWorkflows: "Subscriptions are in the free app; media Library management and players are Premium features.",
          license: "Proprietary; official site copyright applies. Core app is free, Premium is optional.",
          telemetryAndAccount: "Core downloads are free without a Premium account; Premium licensing uses an authenticated license portal. No public telemetry statement was found on the product page.",
          releaseActivity: "Official site listed v7.1.12 as current when verified.",
          bestFor: "A polished cross-platform workflow with subscriptions, advanced configurations, and optional paid library tools.",
          limitations: "Not open source; some library, player, theme, and support features require Premium.",
          sources: [
            { label: "Official product and download page", url: "https://www.stacher.io/" },
            { label: "Official changelog", url: "https://changelog.stacher.io/" },
          ],
        },
        {
          id: "yt-dlp",
          name: "yt-dlp CLI",
          shortName: "yt-dlp",
          summary: "The non-GUI baseline: maximum control, automation, and documentation at the cost of a command line.",
          officialUrl: "https://github.com/yt-dlp/yt-dlp",
          verifiedAt,
          filters: ["windows", "cross-platform", "power", "archive", "open-source"],
          platforms: "Windows, macOS, Linux, BSD, and other Python-supported environments.",
          installation: "Standalone binaries, package managers, pip, or source.",
          toolManagement: "Direct yt-dlp updates; FFmpeg and optional runtime dependencies are managed separately.",
          playlists: "Full playlist/channel selection through documented flags and filters.",
          subtitles: "Complete subtitle, metadata, thumbnail, chapter, and post-processing options.",
          cookies: "Cookie files and direct extraction from supported browsers.",
          presets: "Config files, aliases, scripts, and output templates rather than visual presets.",
          queues: "Shell scripts, batch files, schedulers, and external automation.",
          rawLogs: "The raw terminal output is the primary interface, with verbose/debug modes.",
          archiveWorkflows: "Download archive files, match filters, date ranges, output templates, and scripting.",
          license: "The Unlicense.",
          telemetryAndAccount: "No yt-dlp account requirement; it runs locally. Network requests still go to the source platforms you invoke.",
          releaseActivity: "2026.08.19 published August 19, 2026, with nightly builds also available.",
          bestFor: "Automation, exact flags, reproducible scripts, servers, and users comfortable with terminals.",
          limitations: "No built-in desktop GUI; you own the command syntax, dependency setup, and workflow design.",
          sources: [
            { label: "Official project and option reference", url: "https://github.com/yt-dlp/yt-dlp" },
            { label: "Official releases", url: "https://github.com/yt-dlp/yt-dlp/releases" },
          ],
        },
      ],
    },
    {
      type: "heading",
      level: 2,
      id: "how-to-choose",
      text: "How to choose without overthinking it",
    },
    {
      type: "list",
      ordered: true,
      items: [
        "Start with your operating systems. HalalDL is Windows-only; Parabolic, Open Video Downloader, Stacher, Tartube, and yt-dlp itself cover more platforms.",
        "Decide whether you want a one-off downloader or an archive manager. Tartube's database model is excellent when it is actually needed, but it is extra weight for occasional jobs.",
        "Check the failure path. A visible raw log or reproducible CLI command matters when an extractor changes.",
        "Verify the official release, package source, license, and update activity before installing.",
      ],
    },
    {
      type: "heading",
      level: 2,
      id: "open-in-halaldl",
      text: "Queue a link in HalalDL",
    },
    {
      type: "paragraph",
      text: "If HalalDL v0.6.1 or newer is installed, the local handoff can open a valid HTTP(S) media link in the app. It queues the item and waits for your confirmation; it does not start the download automatically.",
    },
    {
      type: "handoff",
      surface: "flagship_comparison",
    },
    {
      type: "heading",
      level: 2,
      id: "safe-download-path",
      text: "Use an official download path",
    },
    {
      type: "paragraph",
      text: "Whatever tool you choose, prefer its official website, package listing, or GitHub Releases. Verify checksums when the project provides them, and treat an unsigned-installer warning as a reason to verify the source rather than search for a random mirror.",
    },
    {
      type: "cta",
      cta: {
        label: "Download HalalDL for Windows",
        href: "/download",
        eventCta: "go_to_download",
      },
    },
  ],
};
