import Link from "next/link";
import { ArrowRight, ClipboardCheck, Download, ExternalLink, FileCheck2, MonitorDown, PackageOpen, RefreshCw, ShieldCheck } from "lucide-react";
import type { GitHubSnapshot } from "@/lib/github";
import { SITE_LINKS } from "@/lib/site";
import { SiteHeader } from "@/components/home/home-header";
import { SubpageRouteStrip } from "@/components/site/subpage-route-strip";
import { CopyCommand } from "@/components/ui/copy-command";
import { ProductRelatedGuides } from "@/components/guides/product-related-guides";
import { ScrollReveal } from "@/components/ui/scroll-reveal";
import { formatMegabytes } from "@/components/home/home-shared";

type WindowsInstallContentProps = { github: GitHubSnapshot };

const firstRunSteps = [
  { number: "01", title: "Open the official release", short: "Start at GitHub Releases.", body: "Use the GitHub Release as the direct source for the newest Full, Lite, and Portable assets.", icon: Download },
  { number: "02", title: "Choose your build", short: "Full is the recommended default.", body: "Full is the recommended first install. Lite and Portable are deliberate alternatives, not upgrades.", icon: PackageOpen },
  { number: "03", title: "Verify if you want the extra check", short: "Match SHA256SUMS.txt.", body: "Use SHA256SUMS.txt from the same release to compare the installer you downloaded.", icon: FileCheck2 },
  { number: "04", title: "Launch with the source nearby", short: "Pause if Windows asks.", body: "If Windows asks for confirmation, verify source plus checksum before deciding how to continue.", icon: MonitorDown },
];

export function WindowsInstallContent({ github }: WindowsInstallContentProps) {
  return (
    <main id="main-content" className="secondary-page overflow-x-hidden">
      <div className="mx-auto max-w-6xl px-5 pb-16 pt-8 sm:px-8 sm:pb-20">
        <SiteHeader currentPage="none" />
        <SubpageRouteStrip currentPage="install" />

        <nav aria-label="Breadcrumb" className="mt-6 flex items-center gap-2 text-sm text-ink-muted"><Link href="/" className="transition-colors hover:text-ink">Home</Link><span>/</span><span className="font-medium text-ink">Install on Windows</span></nav>

        <section className="secondary-hero relative mt-7 overflow-hidden rounded-[2rem] border border-line bg-paper/65 p-6 sm:p-9 lg:p-10">
          <div className="pointer-events-none absolute -left-24 -top-24 h-64 w-64 rounded-full bg-mint/60 blur-3xl" aria-hidden="true" />
          <div className="pointer-events-none absolute right-0 top-1/3 h-52 w-52 rounded-full bg-sky/70 blur-3xl" aria-hidden="true" />
          <div className="relative grid gap-10 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)] lg:items-center">
            <div className="max-w-xl"><div className="eyebrow"><MonitorDown className="h-3.5 w-3.5" /> Windows install guide</div><h1 className="mt-5 font-display text-4xl font-semibold tracking-[-0.04em] text-ink sm:text-5xl lg:text-[3.65rem]">A first run that stays <span className="text-ink-soft">easy to verify.</span></h1><p className="mt-5 text-base leading-relaxed text-ink-soft sm:text-lg">Start with the official release, use Full for the smoothest setup path, and keep the verification route beside you—not buried in a generic warning panel.</p><div className="mt-7 flex flex-wrap gap-3"><a href={github.fullSetupUrl} target="_blank" rel="noreferrer" className="glass-cta inline-flex items-center gap-2 rounded-2xl px-5 py-3.5 text-sm font-semibold transition-all hover:-translate-y-0.5"><Download className="h-4 w-4" />Download Full<ArrowRight className="h-4 w-4" /></a><Link href="/trust/verify-checksum" className="inline-flex items-center gap-2 rounded-2xl border border-line-strong bg-paper-strong px-5 py-3.5 text-sm font-semibold text-ink transition-colors hover:bg-paper"><FileCheck2 className="h-4 w-4" />Verify SHA256</Link></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm font-medium text-ink-soft"><Link href="/compare/full-vs-lite" className="hover:text-ink">Full vs Lite</Link><Link href="/download" className="hover:text-ink">All download options</Link><a href={github.latestReleaseUrl} target="_blank" rel="noreferrer" className="hover:text-ink">Official release <ExternalLink className="ml-1 inline h-3.5 w-3.5" /></a></div></div>

            <aside aria-label="Install path summary" className="rounded-[1.7rem] border border-line bg-paper-strong/80 p-5 shadow-[0_20px_54px_rgba(8,14,23,0.12)] sm:p-6"><div className="flex items-center justify-between border-b border-line pb-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">Quick path</p><p className="mt-1 font-semibold text-ink">Four steps to first run</p></div><span className="rounded-full bg-mint px-3 py-1 text-xs font-semibold text-mint-strong">{github.latestVersion}</span></div><ol className="relative mt-5 space-y-2 before:absolute before:bottom-5 before:left-4 before:top-5 before:w-px before:bg-line">{firstRunSteps.map((step, index) => { const Icon = step.icon; return <li key={step.title} className="relative flex items-start gap-3 rounded-2xl border border-line bg-paper/70 p-3.5 transition-colors hover:bg-paper"><span className={`relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl text-xs font-semibold ${index === 0 ? "bg-mint text-mint-strong" : "bg-paper-strong text-ink-muted"}`}>{step.number}</span><div className="min-w-0"><div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5 text-ink-muted" /><p className="text-sm font-semibold text-ink">{step.title}</p></div><p className="mt-1 text-xs leading-relaxed text-ink-soft">{step.short}</p></div></li>; })}</ol></aside>
          </div>
        </section>

        <section className="pt-16 sm:pt-20"><ScrollReveal><div className="max-w-2xl"><div className="eyebrow"><ClipboardCheck className="h-3.5 w-3.5" /> First-run sequence</div><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.03em] text-ink sm:text-4xl">Four steps, in the order that matters.</h2><p className="mt-4 text-base leading-relaxed text-ink-soft">The site keeps download choice, verification, and the first launch separate so you never need to work out the trust model in the middle of an install.</p></div></ScrollReveal><div className="mt-8 grid gap-4 sm:grid-cols-2">{firstRunSteps.map((step, index) => { const Icon = step.icon; return <ScrollReveal key={step.title} delay={index * 0.06} className="surface-card-static rounded-[1.55rem] p-5"><div className="flex items-start gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-sky text-sm font-semibold text-sky-strong">{step.number}</span><div><Icon className="h-4 w-4 text-mint-strong" /><h3 className="mt-3 font-display text-xl font-semibold text-ink">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-soft">{step.body}</p></div></div></ScrollReveal>; })}</div></section>

        <section className="pt-16 sm:pt-20"><div className="section-divider mb-12" /><ScrollReveal className="grid gap-5 lg:grid-cols-[1.05fr_0.95fr]"><article className="rounded-[1.75rem] border border-mint-strong/25 bg-mint/25 p-6 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-mint-strong">Recommended starting point</p><h2 className="mt-3 font-display text-3xl font-semibold text-ink">Full gets you into the app sooner.</h2><p className="mt-4 max-w-2xl text-base leading-relaxed text-ink-soft">The Full setup path is the right default when your goal is to use HalalDL rather than actively control every supporting tool. The current installer is {formatMegabytes(github.fullSetupSize)}.</p><a href={github.fullSetupUrl} target="_blank" rel="noreferrer" className="glass-cta mt-6 inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition-transform hover:-translate-y-0.5">Download Full <ArrowRight className="h-4 w-4" /></a></article><article className="surface-card-static rounded-[1.75rem] p-6 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">Convenience path</p><h2 className="mt-3 font-display text-3xl font-semibold text-ink">WinGet is useful—just not the release authority.</h2><p className="mt-4 text-base leading-relaxed text-ink-soft">Use WinGet when its update rhythm fits your setup. When you want the newest asset or checksum first, go to the GitHub Release.</p><div className="mt-6"><CopyCommand command={SITE_LINKS.wingetCommand} /></div></article></ScrollReveal></section>

        <section className="pt-16 sm:pt-20"><ScrollReveal className="grid gap-5 lg:grid-cols-2"><article className="surface-card-static rounded-[1.75rem] p-6 sm:p-7"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-sky"><RefreshCw className="h-5 w-5 text-sky-strong" /></div><div><h2 className="font-display text-2xl font-semibold text-ink">How updates work later</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">Full and Lite continue through the installer path. Portable stays manual by design: download the new ZIP, replace the folder, and keep the app self-contained.</p><Link href="/compare/full-vs-lite" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-ink hover:text-ink-soft">Compare update paths <ArrowRight className="h-4 w-4" /></Link></div></div></article><article className="surface-card-static rounded-[1.75rem] p-6 sm:p-7"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-amber"><ShieldCheck className="h-5 w-5 text-amber-strong" /></div><div><h2 className="font-display text-2xl font-semibold text-ink">If SmartScreen appears</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">Treat it as a prompt to check provenance—not an instruction to ignore it. Confirm GitHub Releases, open the matching SHA256SUMS.txt, and compare the installer hash first.</p><Link href="/trust/verify-checksum" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-ink hover:text-ink-soft">Open verification guide <ArrowRight className="h-4 w-4" /></Link></div></div></article></ScrollReveal></section>

        <ProductRelatedGuides slug="install-halaldl-windows" />
      </div>
    </main>
  );
}
